zn "%SYS"
do ##class(%SYSTEM.License).Upgrade()
do ##class(SYS.Container).QuiesceForBundling()
do ##class(Security.Users).UnExpireUserPasswords("*")

zn "MUS"
set sc = $SYSTEM.OBJ.LoadDir("/opt/irisapp/src/Tartessos", "ck", , 1)
set production = "Tartessos.Production"
set ^Ens.Configuration("csp","LastProduction") = production
do ##class(Ens.Director).SetAutoStart(production)
do ##class(Ens.Director).StartProduction(production)